### ISSUE TITLE
Allow circular preview

### ISSUE THREAD

**Issue by peterver** [peterver/image-crop#4]
Add an extra handle cb and option to provide developers with the possibility to provide a circular preview.

This is much used to preview avatar images ( as they are shown in a circular form most of the time.

**Comment by CanRau** [comment]
Nice script thank you @peterver! Are there any news on the circular preview?

**Comment by peterver** [comment]
going to look into it somewhere tomorrow evening :]

**Comment by CanRau** [comment]
don't wanna hurry you, but would love to use your extremely small cropper :)

**Comment by peterver** [comment]
damn, i completely forgot about this issue, my bad. I've got some time on my hand this weekend. will look into it !

**Comment by CanRau** [comment]
great :)

**Comment by peterver** [comment]
started working on it, not yet finished though

will release asap ^.^

**Comment by CanRau** [comment]
Sounds good :D
Just let me know by commenting here ;-)

**Comment by peterver** [comment]
closing this issue as added in [1.1](https://github.com/peterver/image-crop/releases/tag/1.1), tell me what you think about it :] ?

**Comment by CanRau** [comment]
yeah think that does the job :) thank you!
now I just need to switch from croppie to your nice work, which is about a quarter of the size (spoiler^^)
unfortunately it's a closed community so I won't be able to show you in action :/

**Comment by peterver** [comment]
i know what you're talking about, i built this component for the webapp that we're developping at Skedify. We were originally using ngImgCrop, but it just didn't do the job well enough, and its about 5x the size of this one. Oh well :').

Should you have any more feature requests or issues that you encounter, be sure to create an issue for them :], always happy to improve this little package
